### PR TITLE
Dev Fallout 4 Clean Data and Taglist Generator Update

### PR DESCRIPTION
**Pull request by Sharlikran**
This pull request would handle adding the current API for LOOT API 0.9.0 (although loot32.dll says 0.8.1) g44a0d85 and the taglist generator.

As stated in the Beth forum I am disinterested in working with this project.  I wish you good fortune and luck on your endeavors.  Your work on this project is greatly needed and appreciated.

Also the taglist generator will fail for Fallout 3 and Fallout New Vegas because the destination folders don't exist under Bash Patches.  However, the taglist.yaml files are current as of 5-24-2016 for Skyrim, Oblivion, and Fallout 4 despite the fact that no patchers are enabled for Fallout 4.

### CODE REVIEW

**Comment by Utumno** [comment]
Alright - this would fix #299 too ?

My problem as I explained in the loot discussion all over is that by committing binary files I pollute the repository (nothing is removed from a git repository history, so committing those files that worth some megabytes (!!) this stays in for ever, slowing down the git operations, slowing down clones etc etc - plus it is quite unprofessional) - so I want to keep binary files commits to a minimum, while I look at ways of finally cleaning up the repository (#199) - but that's advanced git (submodules etc) and may invalidate all forks - so I have to proceed carefully.

So is this release stable enough ? Or will I have to commit another loot dll in a couple weeks ? I thing is worth waiting for a hotfixes

Also - will this run for people using XP (which whether we want it or not are a good deal of our Oblivion users) ?

**Comment by Utumno** [comment]
Also - does  Added Automatron, Wasteland Workshop, Far Harbor Clean Data depend on the other commit ? or I can cherry pick that ? What it is about ?

**Comment by Sharlikran** [comment]
You know, I forgot something.  I can't update to the LOOT 0.9.0 API because the proper changes have not been made to loot.py to support the 0.9.0 API.  If the 0.9.0 API is used it's going to not import bash tags like was reported in the Beth forums.  Since I don't know python I can't do it.  You will have to read WrinklyNinja's PDF for LOOT.

**Comment by Utumno** [comment]
Does Added Automatron, Wasteland Workshop, Far Harbor Clean Data depend on the other commit ? or I can cherry pick that ? What it is about ?

**Comment by Sharlikran** [comment]
The commit in d82668cedc13e3244618fb50392373860d9ecc71 doesn't depend on anything else.

**Comment by Arthmoor** [comment]
Regarding XP support. I don't think it serves anyone any good anymore to cling to something Microsoft themselves has cast aside over 2 years ago now. People playing Oblivion need to bite the bullet and upgrade to at least Windows 7 if they expect to have a secure PC, much less continued support for most of the other stuff on their systems. If something in XP is holding Bash back, it needs to be cut loose so Bash can continue to advance properly.

**Comment by Utumno** [comment]
Nothing at XP cuts Bash down - alright point taken

**Pull request closed without merging**
