### PR TITLE
Update MelCTDAHandler

### PR DESCRIPTION
**Pull request by Sharlikran**
Update to MelCTDAHandler to properly add compValue to the fids table based on operFlag. This field in the record is not part of the main routine that currently manages the fids based on conditionFunctionData, allConditions, fid1Conditions, fid2Conditions. It is also handled separately and almost in the same manner in xEdit.

### CODE REVIEW

**Comment by Utumno** [comment]
Anyone test this @wrye-bash/active ? @Sharlikran add the comments to the commit message please and repush - I can cherry pick later

**Comment by Utumno** [comment]
Also add the doc strings inside the method as in:

```
def __setInitCastType(self, value):
    """Set castType in __init__ depending on operFlag"""
    if self.__isUint32(value): self.castType = '=B3sIH2siiIIi'
    else: self.castType = '=B3sfH2siiIIi'
```

**Comment by Sharlikran** [comment]
Done

**Comment by Utumno** [comment]
Will merge this and #385 as soon I address the file move dialog - please make sure all is ok meanwhile

**Comment by Infernio** [comment]
@Utumno What happened to this issue, #385 and #389? Were they merged, or should we remove them from the 307 milestone so they don't show up in the final changelog?

**Pull request closed without merging**
