### PR TITLE
Dev fallout patcher update

### PR DESCRIPTION
**Pull request by Sharlikran**
Had to rebuild both the Skyrim and Fallout branches because of the changes to the files and the new location of some of the files.

### CODE REVIEW

**Comment by Sharlikran** [comment]
Pull request #185 closed itself.  I could not do much about it since I had to rebuild everything after your latest refactoring.  When file locations or file names change I have to redo everything it does not merge or rebase.

I don't know what to do really.  I want to keep all the branches current with dev but if it's going to be an issue then maybe I'll just wait until you are all done.

**Comment by Arthmoor** [comment]
Heh, if you're lost, imagine how those of us even less familiar with how GitHub works feel :P

**Comment by Sharlikran** [comment]
```Python
class MelAlternateTextures(MelBase):
    """Represents a set of alternate textures element."""
    def __init__(self,type,attr,default=None):
        """Initialize."""
        MelBase.__init__(self,type,attr,default)
        self._debug = False
    def hasFids(self,formElements):
        """Include self if has fids."""
        formElements.add(self)
    def loadData(self,record,ins,type,size,readId):
        """Reads data from ins into record attribute."""
        textures = []
        numTextures, = struct.unpack('I',ins.read(4,readId))
        for count in range(numTextures):
            size, = struct.unpack('I',ins.read(4,readId))
            name = ins.readString(size,readId)
            fid = ins.unpackRef(readId)
            index, = struct.unpack('I',ins.read(4,readId))
            textures.append((name,fid,index))
        record.__setattr__(self.attr,textures)
        if self._debug: print ' ',record.__getattribute__(self.attr)
    def dumpData(self,record,out):
        """Dumps data from record to outstream."""
        textures = record.__getattribute__(self.attr)
        if not textures: return
        data = ''
        data += struct.pack('=I',len(textures))
        for name,fid,index in textures:
            data += struct.pack('=I',len(name))
            data += _encode(name,firstEncoding=bolt.pluginEncoding)
            data += struct.pack('=I',fid)
            data += struct.pack('=I',index)
        out.packSub(self.subType,data)
    def mapFids(self,record,function,save=False):
        """Applies function to fids. If save is true, then fid is set
        to result of function."""
        results = []
        targets = record.__getattribute__(self.attr)
        if not targets: return
        for name,fid,index in targets:
            result = function(fid)
            results.append((name,result,index))
        if save:
            record.__setattr__(self.attr,results)
```
With the above routine I get the following error
```Auto
brec.py 1271 dumpData: error dumping data:
Traceback (most recent call last):
  File "bash\brec.py", line 1269, in dumpData
    element.dumpData(record,out)
  File "bash\brec.py", line 757, in dumpData
    element.dumpData(target,out)
  File "bash\game\falloutnv\records.py", line 577, in dumpData
    data += _encode(name,firstEncoding=bolt.pluginEncoding)
NameError: global name 'bolt' is not defined
```
I probably add
```Python
import ... bolt
from ...bolt import StateError, Flags, BoltError, sio, DataDict, winNewLines, \
    _unicode, _encode, GPath
```
However is there a better way to resolve the issue I have with the line ``data += _encode(name,firstEncoding=bolt.pluginEncoding)``?

**Comment by Sharlikran** [comment]
Would it be?
```Python
self.encoding = bosh.settings['bash.pluginEncoding']
data += _encode(name,firstEncoding=self.encoding)
```
I'm probably going to get an error that bosh isn't defined, aren't I?

**Comment by Utumno** [comment]
`from ... import bolt`

I don't know what's the diff between `bosh.settings['bash.pluginEncoding']` and `bolt.pluginEncoding`

**Comment by Utumno** [comment]
Also `self.encoding = bosh.settings['bash.pluginEncoding']` will have the side effect of adding an attribute to MelAlternateTextures - you probably don't want that. `encoding = bosh.settings['bash.pluginEncoding']
data += _encode(name,firstEncoding=encoding)` should be enough (would work too - but better go with `from ... import bolt`

**Comment by Utumno** [comment]
So this is the branch you want rebased ? Fallout specific stuff starts from https://github.com/Sharlikran/wrye-bash/commit/596861fad3ccbec2216c46f83f7644c1c7e1e0fe ?

**Comment by Sharlikran** [comment]
This branch is fine, I'm pretty sure.  I'm at my daughters school dance I'll double check later.

**Comment by Sharlikran** [comment]
Yes you are right, the Fallout stuff starts at https://github.com/Sharlikran/wrye-bash/commit/596861fad3ccbec2216c46f83f7644c1c7e1e0fe but it's fine.  In fact my test version is running smoothly.

**Comment by Sharlikran** [comment]
Okay so now I see a potential issue now.  Since you have moved things around for Skyrim as far as constants and such now none of the Fallout changes match the changes for Skyrim and Oblivion.  So I may have rebased everything correctly but it won't be correct until I update fallout's layout to match Skyrim and Oblivion.

This also makes it harder to add Fallout 4 support for BAIN.

**Comment by Sharlikran** [comment]
Okay so now I see a potential issue now.  Since you have moved things around for Skyrim as far as constants and such now none of the Fallout changes match the changes for Skyrim and Oblivion.  So I may have rebased everything correctly but it won't be correct until I update fallout's layout to match Skyrim and Oblivion.

This also makes it harder to add Fallout 4 support for BAIN.

**Comment by Sharlikran** [comment]
I think I was able to fix it by the seat of my pants...  :-1:

**Comment by Sharlikran** [comment]
My changes are going to cause a bunch of conflicts and regression if I rebase things.

For Example this change in patch_files.py

Original:
```Python
def __init__(self,modInfo,patchers):
        """Initialization."""
        ModFile.__init__(self,modInfo,None)
        self.tes4.author = u'BASHED PATCH'
        self.tes4.masters = [bosh.modInfos.masterName]
        self.longFids = True
        #--New attrs
        self.aliases = {} #--Aliases from one mod name to another. Used by text file patchers.
        self.patchers = patchers
        self.keepIds = set()
        self.mergeIds = set()
        self.loadErrorMods = []
        self.worldOrphanMods = []
        self.unFilteredMods = []
        self.compiledAllMods = []
        self.patcher_mod_skipcount = {}
        #--Config
        if bush.game.fsName in (u'FalloutNV', u'Fallout3',):
            self.bodyTags = 'HAGPBFE' #--Default bodytags
        else:
            self.bodyTags = 'ARGHTCCPBS' #--Default bodytags
        #--Mods
        dex = bosh.modInfos.loIndexCached
        loadMods = [name for name in bosh.modInfos.activeCached
                    if dex(name) < dex(PatchFile.patchName)]
        if not loadMods:
            raise BoltError(u"No active mods dated before the bashed patch")
        self.setMods(loadMods, [])
        for patcher in self.patchers:
            patcher.initPatchFile(self,loadMods)
```

New code:
```Python
#--Instance
    def __init__(self,modInfo,patchers):
        """Initialization."""
        ModFile.__init__(self,modInfo,None)
        self.tes4.author = u'BASHED PATCH'
        self.tes4.masters = [bosh.modInfos.masterName]
        self.longFids = True
        self.keepIds = set()
        _PFile.__init__(self, patchers)
```

And my changes were:
```Python
        if bush.game.fsName in (u'FalloutNV', u'Fallout3',):
            self.bodyTags = 'HAGPBFE' #--Default bodytags
        else:
            self.bodyTags = 'ARGHTCCPBS' #--Default bodytags
```
No idea what to do at this point.  This is why I stopped working on things a while back.  Until all refactoring stops I can't keep up with the changes.  I wouldn't be surprised if my rebasing is why there are errors when people go to the installers tab for Fallout 4.

**Comment by Sharlikran** [comment]
I think I am gonna make a backup of everything and just start over tomorrow.  I probably have to delete all the branches.  Not sure yet I'll look at Gitk in the morning.

**Comment by Sharlikran** [comment]
I think your help getting the interactive rebasing will help. Thanks again for your advice.  I think I got it fixed.  I just have to check it.

**Comment by Utumno** [comment]
Put to the backburner - fallout3 is post 307

**Pull request closed without merging**
