### PR TITLE
Update supported versions

### PR DESCRIPTION
**Pull request by Arthmoor**

### CODE REVIEW

**Comment by Utumno** [comment]
I keep this to merge before next release

**Comment by Utumno** [comment]
@CptMcSplody although I appreciate someone trying to clean things up please let me know before pushing to dev. This one is for instance the latest versions? Also I would have squashed the three loot commits together as they belong together. I try to keep dev commits low and as needed, cause it allows better blaming, viewing and in general navigating the tree

**Comment by Utumno** [comment]
I also try to keep the history linear for the same reasons, which you did here (a merge commit for a pull request like this is amateurish) - thanks!

**Comment by CptMcSplody** [comment]
@Utumno It's pretty simple to drop the commits and redo them. I need those changes if I'm working on the patchers and I'd rather not have to prune them each time I want to fix something.

**Comment by Utumno** [comment]
Well the policy is the dev branch is the stable one so we don't rewrite history on it. It's ok and actually having other people commit to dev is welcome - but just the first few times let me know so I review

Btw your branches were gone?

Thanks!

**Comment by CptMcSplody** [comment]
> so we don't rewrite history on it

It shouldn't make a difference since it's the end, your choice anyhow.

> Btw your branches were gone?

Have to redo them a bit, going to wait for those changes you are working on to be pushed.

And the set verses list issue you queried, what I meant by order matters, is it matters for the sets.
ITM records are produced if you don't sort the sets before comparing. The actual records are stored in whatever order in the plug-in, As for the actual sorting, there are ways to trim the actual number of times it has to be used when checking the regions. The number of records within each set is also quite low, 0-10, with empty records being more common.

There are bigger fish to fry though, there are some sections of code that could be simplified.

**Comment by Utumno** [comment]
There must be another reason for this @CptMcSplody - this simply can't be, a difference between sets can't possibly take order into account, it's the definition of set

**Comment by CptMcSplody** [comment]
I'm going through it later, so I'll post the results from both runs.

**Comment by Utumno** [comment]
Thanks @CptMcSplody

**Pull request merged**
