### PR TITLE
Remove Gimpshop; Add Krita

### PR DESCRIPTION
**Pull request by Metallicow**
I believe this is correct. Just swaped gimpshop for krita.

### CODE REVIEW

**Comment by Arthmoor** [comment]
@Utumno This pull request appears to be quite old. Is it still something that's under consideration?

**Comment by Utumno** [comment]
I can merge this if we want to drop gimpshop - I guess @Metallicow had his reasons

**Comment by Arthmoor** [comment]
If "Gimpshop" refers to the GIMP image editor then I see no reason to drop that. No objection to adding one for Krita though either.

**Comment by Utumno** [comment]
Does it refer to that ?

**Comment by Arthmoor** [comment]
Nope. Should have Googled it sooner, but it's apparently a dead fork of GIMP that hasn't been updated since 2006.

**Comment by Metallicow** [comment]
Umm ya Gimpshop was a fork which eventually stopped development, then someone riddled the remaining available sources with crapware. Krita is essentially the open source equivalent to Photoshop and GIMP combo focused more on artists and is a official non-for-profit and is supported unlike the Gimpshop which the dev basically fell of the earth. The new versions of GIMP have a windowed mode that makes them more like photoshop, so yea the work that was done with gimpshop is beginning to be outdated very quickly.

**Comment by Infernio** [comment]
@Utumno Added the requested NSIS changes.

**Comment by Utumno** [comment]
> If you have no objections, then I'd like to merge it and finally close this PR from 2015 :P

Oh yes please! :)

**Pull request merged**
