### PR TITLE
Dev fallout patcher update

### PR DESCRIPTION
**Pull request by Sharlikran**
Here is my Fallout submission, but it is untested so I will have to make changes.

I tried to make the branches like so:

``` Auto
dev
   \ - dev-skyrim-patcher-update
                                \ - dev-fallout-patcher-update
```

@Utumno Did I do that correctly so that I rebase dev-skyrim-patcher-update off of dev, then I rebase dev-fallout-patcher-update off of dev-skyrim-patcher-update and you were saying I should be able to keep everything in sync.  Correct?

### CODE REVIEW

**Comment by Sharlikran** [comment]
@Utumno Okay I made the changes so that the Fallout New Vegas version will open.  I am biting my nails now though because there is no contextual menu on the mods tab and the installers tab doesn't work.  This was the same behavior for Skyrim at first until you changed something.  What did you change?  Can you go to my fork and make the same changes?

Also, can you go to my fork and Squash all the Added Fallout Support Commits into one?  I just want it to say Added Fallout Patcher Support.

Can you help me with that please?

**Comment by Utumno** [comment]
Thanks for doing it!
Will get back to you ASAP - but for the moment:
 - for the fix check the dev branch
- The one thing I want you to do is concentrate on the Skyrim patchers so they will hopefully make it into 306 - I do not have time to set up patches + I was never a patch expert and my  TES5 skills are rusty as hell. So I would like you  to test the TES5 patchers - and post all your findings to that pull request - do not reply here
- quick look - game specific patchers should go to game packages not into bash.patcher.patchers

Anyway will look into it ASAP but for the moment concentrate on the Skyrim patchers and reply 
to me there

**Comment by Sharlikran** [comment]
> for the fix check the dev branch

None of it made any sense to me since none of the changes were in the Skyrim/Oblivion folders under game.

> quick look - game specific patchers should go to game packages not into bash.patcher.patchers

I have no idea what you mean by that and I don't see a game/packages folder.  Do you mean special.py?

You had mentioned that you can look into this when you have time.  That would be helpful because I can easily see that I have no idea how to get the mods and the installers tabs to work for this branch like you did for Skyrim.

Since I can't make changes to the back end code I need you or other volunteers to do 100% of the back end coding.  If not then there isn't much I can do to help.

**Comment by Sharlikran** [comment]
@Utumo I just noticed there was something left out of the Skyrim/Oblivion branch so I have to add that and then redo the changes.  It will be about the same as squashing all the commits anyway.  So thanks for offering but don't worry about squash the commits for now.

**Comment by Utumno** [comment]
The fix is here: https://github.com/wrye-bash/wrye-bash/commit/144b707a74c6bba504efff9b1a1164e3ac783a44

This is a rebase on an earlier commit from the fix - mystery solved :)

**Comment by Utumno** [comment]
Using the gitk you can very easily compare a branch before and after a rebase: http://stackoverflow.com/a/17549542/281545

**Comment by Sharlikran** [comment]
> This is a rebase on an earlier commit from the fix - mystery solved :)

So after I rebase on dev, from commit 144b707a74c6bba504efff9b1a1164e3ac783a44 it workes.  I had no idea what you were talking about in the above statement.  Even with the GitGui I would not have seen this or known what was going on because I don't understand what the GitGui or the information presented.

I sincerely apologize for all my venting.  I am clearly not ready for write access IMO.  Thanks for all your guidance so far.

**Comment by Sharlikran** [comment]
@Utumno I am going to go find your squash commits instructions.  I believe they were for notepad++.  once I find them, I'll get these squashed.  Thanks for providing those instructions.  I will try to use them.  If I have any issues I'll let you know.

**Comment by Utumno** [comment]
- pull dev on your fork
- fire git Bash (rclick on your repo folder and choose git Bash here)
- fire up gitk (for instance by issuing `gitk --all &` on git bash)
- checkout this branch (you can do it in gitk by rclicking on the branch and choosing "checkout this branch" or in cli `git checkout dev-fallout-patcher-update` - I prefer gitk)
- issue `git rebase --onto dev dev dev-fallout-patcher-update`
- let git rebase
- go to gitk hit F5 to refresh
- you will see the ex commits of the dev-fallout-patcher-update with no branch on them and rebased dev-fallout-patcher-update branch sitting now on dev
- right click on ___dev-skyrim-patcher-update___ and choose checkout this branch
- then go to the _rebased commit ' Added import for bush to fix Stats Patcher'_ - rclick choose _Reset dev-skyrim-patcher-update here_
- in the dialog choose Hard

Now you have dev-skyrim-patcher-update rebased on dev and dev-fallout-patcher-update rebased on top of it. Fixes are included from dev

Post back here and I will guide you to squash the commits

**Comment by Utumno** [comment]
Git gui is used for committing - you can see the lines changed, select lines to commit, commit etc
Do see: http://nathanj.github.io/gitguide/committing.html

_Gitk_ is used to see the branches - github web ui is no substitute

Had you used this you would have seen that I fixed the bugs with mods and installers

No need to apologize but from now on please follow my instructions - let;s waste no more time (plus all the fixes in dev branch were not included in this rebase here so you were scratching your head in vain).

Always look at gitk - all the info is there, plus by right clicking you can compare commits which is necessary before and after the rebases: http://stackoverflow.com/a/17549542/281545

Posted instructions on how to really rebase on dev in issue #185 - do this and then I will post instructions on rebase interactive (squashing)

**Comment by Utumno** [comment]
- pull dev on your fork
- fire git Bash (rclick on your repo folder and choose git Bash here)
- fire up gitk (for instance by issuing `gitk --all &` on git bash)
- checkout this branch (you can do it in gitk by rclicking on the branch and choosing "checkout this branch" or in cli `git checkout dev-fallout-patcher-update` - I prefer gitk)
- issue `git rebase --onto dev dev dev-fallout-patcher-update`
- let git rebase
- go to gitk hit F5 to refresh
- you will see the ex commits of the dev-fallout-patcher-update with no branch on them and rebased dev-fallout-patcher-update branch sitting now on dev
- right click on ___dev-skyrim-patcher-update___ and choose checkout this branch
- then go to the _rebased commit ' Added import for bush to fix Stats Patcher'_ - rclick choose _Reset dev-skyrim-patcher-update here_
- in the dialog choose Hard

Now you have dev-skyrim-patcher-update rebased on dev and dev-fallout-patcher-update rebased on top of it. Fixes are included from dev

Post back here and I will guide you to squash the commits

**Comment by Sharlikran** [comment]
> No need to apologize but from now on please follow my instructions - let;s waste no more time

Thanks but yes I do.  I just caused a bunch of undue stress and frustration for you.  I'll just leave it at that.

Anyway my daughter had to stay home from school and I have to change my Radiator today since it's payday.  I'll get to this when I'm done.  Thanks for letting me know that some of what is in this branch does not include the changes in dev.  I had this issue before when wrinkly made the feature-fallout-support branch.  Just a plain automatic rebse was not working and he ended up doing it himself.  I guess it's happening now as well so I'll see what I can do.  Thanks again.

**Comment by Sharlikran** [comment]
If you feel that this branch would force dev to loose your changes, is there a screen shot of what I am loosing from dev, for just the Skyrim branch.

Here is a list of files that I changed in this branch:

Modified:

[M] Mopy/Bash Patches/Skyrim/taglist.yaml
[M] Mopy/bash/basher/app_buttons.py
[M] Mopy/bash/basher/constants.py
[M] Mopy/bash/basher/gui_patchers.py
[M] Mopy/bash/basher/links.py
[M] Mopy/bash/basher/mod_links.py
[M] Mopy/bash/basher/patcher_dialog.py
[M] Mopy/bash/bish.py
[M] Mopy/bash/bosh.py
[M] Mopy/bash/brec.py
[M] Mopy/bash/game/game.template
[M] Mopy/bash/game/oblivion/__init__.py
[M] Mopy/bash/game/skyrim/__init__.py
[M] Mopy/bash/game/skyrim/records.py
[M] Mopy/bash/patcher/patchers/importers.py
[M] Mopy/bash/patcher/patchers/special.py
[M] Mopy/bash/patcher/record_groups.py
[M] Mopy/bash/patcher/utilities.py

Added, New files

[N] Mopy/bash/game/fallout3/__init__.py
[N] Mopy/bash/game/fallout3/constants.py
[N] Mopy/bash/game/fallout3/patcher/__init__.py
[N] Mopy/bash/game/fallout3/records.py
[N] Mopy/bash/game/falloutnv/__init__.py
[N] Mopy/bash/game/falloutnv/constants.py
[N] Mopy/bash/game/falloutnv/patcher/__init__.py
[N] Mopy/bash/game/falloutnv/records.py
[N] Mopy/bash/images/fallout316.png
[N] Mopy/bash/images/fallout324.png
[N] Mopy/bash/images/fallout332.png
[N] Mopy/bash/images/falloutnv16.png
[N] Mopy/bash/images/falloutnv24.png
[N] Mopy/bash/images/falloutnv32.png
[N] Mopy/bash/images/geck16.png
[N] Mopy/bash/images/geck24.png
[N] Mopy/bash/images/geck32.png
[N] Mopy/bash/images/tools/fnv4gb16.png
[N] Mopy/bash/images/tools/fnv4gb24.png
[N] Mopy/bash/images/tools/fnv4gb32.png
[N] Mopy/bash/images/tools/fnvedit16.png
[N] Mopy/bash/images/tools/fnvedit24.png
[N] Mopy/bash/images/tools/fnvedit32.png
[N] Mopy/bash/images/tools/fnvmasterrestore16.png
[N] Mopy/bash/images/tools/fnvmasterrestore24.png
[N] Mopy/bash/images/tools/fnvmasterrestore32.png
[N] Mopy/bash/images/tools/fnvmasterupdate16.png
[N] Mopy/bash/images/tools/fnvmasterupdate24.png
[N] Mopy/bash/images/tools/fnvmasterupdate32.png
[N] Mopy/bash/images/tools/fo3edit16.png
[N] Mopy/bash/images/tools/fo3edit24.png
[N] Mopy/bash/images/tools/fo3edit32.png
[N] Mopy/bash/images/tools/fo3masterrestore16.png
[N] Mopy/bash/images/tools/fo3masterrestore24.png
[N] Mopy/bash/images/tools/fo3masterrestore32.png
[N] Mopy/bash/images/tools/fo3masterupdate16.png
[N] Mopy/bash/images/tools/fo3masterupdate24.png
[N] Mopy/bash/images/tools/fo3masterupdate32.png
[N] Mopy/bash/images/tools/fomm16.png
[N] Mopy/bash/images/tools/fomm24.png
[N] Mopy/bash/images/tools/fomm32.png
[N] Mopy/bash/images/tools/masterrestore16.png
[N] Mopy/bash/images/tools/masterrestore24.png
[N] Mopy/bash/images/tools/masterrestore32.png
[N] Mopy/bash/images/tools/masterupdate16.png
[N] Mopy/bash/images/tools/masterupdate24.png
[N] Mopy/bash/images/tools/masterupdate32.png
[N] Mopy/bash/l10n/Japanese.txt

**Pull request closed without merging**
